version: "3.9"

services:
  db:
    image: docker.io/postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=acessoaoadmin
      - POSTGRES_DB=volley_db
    volumes:
      - raizes_db:/home/luwpy/.sql/postgres

volumes:
  raizes_db:
